In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [4]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [5]:
myGroceries = pd.read_csv("/anvil/projects/tdm/data/8451/The_Complete_Journey_2_Master/5000_transactions.csv")

In [7]:
# Assign Column Names - Renames the columns of the myGroceries DataFrame to
# ensure that column names are easy to work with and follow a standardized format.

In [8]:
myGroceries.columns = ["BASKET_NUM", "HSHD_NUM", "PURCHASE", "PRODUCT_NUM", "SPEND", "UNITS", "STORE_R", "WEEK_NUM", "YEAR"]

In [9]:
# Step 4 - # Display first 5 rows of data from the Gorcery Transaction data frame(similar to Top 5 in sql) - click run

In [10]:
myGroceries.head()

,BASKET_NUM,HSHD_NUM,PURCHASE,PRODUCT_NUM,SPEND,UNITS,STORE_R,WEEK_NUM,YEAR
0,24,1809,03-JAN-16,5817389,-1.50,-1,SOUTH,1,2016
1,24,1809,03-JAN-16,5829886,-1.50,-1,SOUTH,1,2016
2,34,1253,03-JAN-16,539501,2.19,1,EAST,1,2016
3,60,1595,03-JAN-16,5260099,0.99,1,WEST,1,2016
4,60,1595,03-JAN-16,4535660,2.50,2,WEST,1,2016

In [11]:
#Set display option to show all columns - Configures Pandas to display all columns of a DataFrame when printed or 
#displayed in an interactive environment (e.g., Jupyter Notebook)

In [12]:
pd.set_option('display.max_columns',None)
#pd.set_option(): A Pandas function used to configure global display options.
#display.max_columns: Specifies the option to control the maximum number of columns displayed.
#None: Sets the option to display all columns, regardless of how many there are
myGroceries

,BASKET_NUM,HSHD_NUM,PURCHASE,PRODUCT_NUM,SPEND,UNITS,STORE_R,WEEK_NUM,YEAR
0,24,1809,03-JAN-16,5817389,-1.50,-1,SOUTH,1,2016
1,24,1809,03-JAN-16,5829886,-1.50,-1,SOUTH,1,2016
2,34,1253,03-JAN-16,539501,2.19,1,EAST,1,2016
3,60,1595,03-JAN-16,5260099,0.99,1,WEST,1,2016
4,60,1595,03-JAN-16,4535660,2.50,2,WEST,1,2016
...,...,...,...,...,...,...,...,...,...
10625548,103429,2164,29-DEC-17,6602908,4.99,1,WEST,104,2017
10625549,103433,3413,29-DEC-17,3759093,2.00,2,SOUTH,104,2017
10625550,103433,3413,29-DEC-17,5709849,5.99,1,SOUTH,104,2017
10625551,103437,3817,29-DEC-17,2474555,1.79,1,SOUTH,104,2017
10625552,103537,644,30-DEC-17,3759136,2.00,2,CENTRAL,104,2017

In [13]:
#Group by 'PRODUCT_NUM' and calculate sum "Total"'Spend' - Groups the grocery store product transactions DataFrame by product (PRODUCT_NUM), 
#calculates the sum (Total_Spend) for each PRODUCT_NUM, sort the values, call the last 10 rows of data, and resets the index and renames the aggregated column as Total_Spend

In [48]:
pd.set_option('display.max_rows',None)
myTop10_Prod=myGroceries.groupby('PRODUCT_NUM')['SPEND'].sum().sort_values().tail(10).reset_index(name='Total_Spend')
#Groups the data by the PRODUCT_NUM column (representing product numbers)
#Aggregates (sums) the SPEND column for each product group to calculate total spend per product
#Sorts the aggregated total spend values in ascending order
#Selects the top 10 products with the highest total spend by taking the last 10 rows of the sorted data
#Resets the index and renames the aggregated column as Total_Spend

In [ ]:
# Displays the resulting DataFrame (myTop10_Prod) containing the top 10 products with there total spend values.

In [49]:
myTop10_Prod

   PRODUCT_NUM  Total_Spend
0        89415     50032.42
1         8523     53845.65
2      1344763     58170.84
3      4889358     63823.61
4        85201     65605.34
5       766108     66085.00
6        74424     75787.49
7        85311    102928.59
8      1367192    111433.78
9         8511    131399.78

In [ ]:
# Sorts the myTop10_Prod DataFrame by the Total_Spend column in descending order (ascending=False) to display products with the highest spend at the top.

In [50]:
myTop10_Prod.sort_values(by='Total_Spend',ascending=False)

   PRODUCT_NUM  Total_Spend
9         8511    131399.78
8      1367192    111433.78
7        85311    102928.59
6        74424     75787.49
5       766108     66085.00
4        85201     65605.34
3      4889358     63823.61
2      1344763     58170.84
1         8523     53845.65
0        89415     50032.42