In [1]:
# Step 1 - Import Required Library -The pandas library is imported(the pd is an alias for pandas - similar to database in sql) - click run

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [4]:
# Step 2 - # read_csv File Data to be loaded into pandas Data Frame (similar to tables in sql) - click run

In [5]:
myElection_Donations = pd.read_csv("/anvil/projects/tdm/data/election/itcont1980.txt", header=None, sep='|') #header=None: Indicates that the file does not contain column headers. Without this, Pandas will assume the first row contains column names.
#sep='|': Specifies that the columns in the file are separated by a pipe (|) character.

In [6]:
# Step 3 - Assign Column Names

In [7]:
myElection_Donations.columns = ["CMTE_ID", "AMNDT_IND", "RPT_TP", "TRANSACTION_PGI", "IMAGE_NUM", "TRANSACTION_TP", "ENTITY_TP", "NAME", "CITY", "STATE", "ZIP_CODE", "EMPLOYER", "OCCUPATION", "TRANSACTION_DT", "TRANSACTION_AMT", "OTHER_ID", "TRAN_ID", "FILE_NUM", "MEMO_CD", "MEMO_TEXT", "SUB_ID"]
#myElection_Donations.columns: Replaces the default column names (e.g., integers) with meaningful names based on the dataset's structure

In [8]:
# Step 4 - # Display first 5 rows of data from the election donations data frame(similar to Top 5 in sql) - click run

In [9]:
myElection_Donations.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,EMPLOYER,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00078279,A,M11,P,80031492155,22Y,NaN,"MCKENNON, K R",MIDLAND,MI,...,NaN,NaN,10031979.0,400,NaN,NaN,NaN,NaN,CONTRIBUTION REF TO INDIVIDUAL,3062020110011466469
1,C00078279,A,M11,NaN,79031415137,15,NaN,"OREFFICE, P",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1500,NaN,NaN,NaN,NaN,NaN,3061920110000382948
2,C00078279,A,M11,NaN,79031415137,15,NaN,"DOWNEY, J",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,300,NaN,NaN,NaN,NaN,NaN,3061920110000382949
3,C00078279,A,M11,NaN,79031415137,15,NaN,"BLAIR, E",MIDLAND,MI,...,DOW CHEMICAL CO,NaN,10261979.0,1000,NaN,NaN,NaN,NaN,NaN,3061920110000382950
4,C00078287,A,Q1,NaN,79031231889,15,NaN,"BLANCHARD, JOHN A",CHICAGO,IL,...,NaN,NaN,3201979.0,200,NaN,NaN,NaN,NaN,NaN,3061920110000383914

In [10]:
#Combines the CITY and STATE columns into a single string in the format CITY, STATE
#Group the data by this combined string to aggregate donation amounts (TRANSACTION_AMT) for each city-state pair
#The dropna=False ensures that rows with missing values in either column are not excluded from the grouping process
#Calclates the donation amounts (TRANSACTION_AMT) for each group (city-state pair) by summing them
#Rename the calculated column (TRANSACTION_AMT) to DONATION_AMT for clarity
#Select the last 21 rows of the grouped and aggregated DataFrame
#Sort the resulting DataFrame by the DONATION_AMT column in descending order (ascending=False), so cities/states with the highest total donations appear at the top.

In [11]:
myElection_Donations.groupby(myElection_Donations['CITY'] + ', ' + myElection_Donations['STATE'], dropna = False)['TRANSACTION_AMT'].sum().reset_index(name='DONATION_AMT').tail(41).sort_values(by='DONATION_AMT',ascending=False)

                     index  DONATION_AMT
19521                  NaN      18092711
19512       ZIONSVILLE, IN         26604
19488        YUBA CITY, CA         18745
19498       ZANESVILLE, OH         15365
19494            YUKON, OK         12536
19495             YUMA, AZ          9976
19506      ZEPHYR COVE, NV          8449
19510           ZILLAH, WA          6370
19509      ZEPHYRHILLS, FL          6020
19481        YOUNSTOWN, OH          5500
19486        YPSILANTI, MI          4475
19514        ZIONVILLE, IN          3650
19504           ZENITH, WA          2990
19492          YUCAIPA, CA          2923
19501          ZEELAND, MI          2455
19483       YOUNTVILLE, CA          2400
19500          ZEBULON, NC          1700
19513       ZIONSVILLE, PA          1250
19515       ZIONVILLLE, IN          1000
19497  Z E BATON ROUGE, LA          1000
19493     YUCCA VALLEY, CA           950
19507     ZEPHYR HILLS, FL           800
19508      ZEPHYRHILIS, FL           725
19518           ZWOLLE, LA           700
19519     [AULS VALLEY, OK           500
19517         ZUMBROTA, MN           500
19503         ZELLWOOD, FL           500
19502           ZEINTH, WA           500
19520        [NCHORAGE, AK           500
19499          ZEBULON, GA           500
19511             ZION, IL           500
19487            YREKA, CA           500
19485         YPSALANI, MI           390
19491          YUCAFIA, CA           300
19484          YOUSTON, TX           250
19516       ZRONSVILLE, IN           250
19490         YUBXCITY, CA           250
19505          ZEPHYER, TX           250
19489         YUBACITY, CA           250
19482       YOUNTSTOWN, OH           250
19496             YUMA, CO           250

In [12]:
pd.set_option('display.max_rows',None)
# task a: Find top 41 cities in Indiana by number of donations
# Filter for Indiana records and count donations by city
indiana_donations = myElection_Donations[myElection_Donations['STATE'] == "IN"]

In [13]:
# Display results of task a
print("Top 41 Indiana cities by number of donations:")

Top 41 Indiana cities by number of donations:

In [14]:
# Group by city, count records per city, rename count column, sort descending, and take top 41
top_indiana_cities = indiana_donations.groupby('CITY').size().reset_index(name='DONATION_COUNT').sort_values('DONATION_COUNT', ascending=False).head(41)

In [15]:
print(top_indiana_cities)

               CITY  DONATION_COUNT
159    INDIANAPOLIS            1443
239          MUNCIE             232
33           CARMEL             167
108      FORT WAYNE             157
100      EVANSVILLE             151
121        FT WAYNE             132
90          ELKHART             132
314      SOUTH BEND             123
165          INDPLS             123
188       LAFAYETTE              85
328     TERRE HAUTE              75
193         LAPORTE              53
377      ZIONSVILLE              52
124            GARY              47
221    MERRILLVILLE              46
54         COLUMBUS              45
181          KOKOMO              45
287        RICHMOND              43
18      BLOOMINGTON              38
137       GREENWOOD              35
62      CROWN POINT              35
2          ANDERSON              34
338      VALPARAISO              34
240          MUNICE              31
241         MUNSTER              30
349          WABASH              27
358  WEST LAFAYETTE              24
322        SYRACUSE              24
257     NOBLESVILLE              22
142         HAMMOND              22
347     W LAFAYETTE              22
354          WARSAW              21
344       VINCENNES              20
146          HOBART              17
222   MICHIGAN CITY              16
144        HIGHLAND              16
230       MISHAWAKA              16
44       CHESTERTON              15
162     INDIANPOLIS              15
352       WALKERTON              15
275      PLAINFIELD              15

In [16]:
# task b: Using only indexing (without directly referring to myElection_Donations)
# Create a reference variable for indexing purposes
election_data = myElection_Donations  # Reference the same data with different name

# Use .loc indexing to filter Indiana records
indiana_indices = election_data.index[election_data['STATE'] == "IN"]

In [17]:
# Display results of Task b
print(indiana_indices)

Index([    21,    639,    654,    671,    683,   1504,   1581,   1588,   1593,
         1599,
       ...
       307765, 307766, 307767, 307768, 307769, 307864, 307962, 308003, 308479,
       308644],
      dtype='int64', length=4606)

In [18]:
# Group by city, count records per city, rename count column, sort descending, and take top 41
top_indiana_cities = indiana_donations.groupby('CITY').size().reset_index(name='DONATION_COUNT').sort_values('DONATION_COUNT', ascending=False).head(41)

In [19]:
print(top_indiana_cities)

               CITY  DONATION_COUNT
159    INDIANAPOLIS            1443
239          MUNCIE             232
33           CARMEL             167
108      FORT WAYNE             157
100      EVANSVILLE             151
121        FT WAYNE             132
90          ELKHART             132
314      SOUTH BEND             123
165          INDPLS             123
188       LAFAYETTE              85
328     TERRE HAUTE              75
193         LAPORTE              53
377      ZIONSVILLE              52
124            GARY              47
221    MERRILLVILLE              46
54         COLUMBUS              45
181          KOKOMO              45
287        RICHMOND              43
18      BLOOMINGTON              38
137       GREENWOOD              35
62      CROWN POINT              35
2          ANDERSON              34
338      VALPARAISO              34
240          MUNICE              31
241         MUNSTER              30
349          WABASH              27
358  WEST LAFAYETTE              24
322        SYRACUSE              24
257     NOBLESVILLE              22
142         HAMMOND              22
347     W LAFAYETTE              22
354          WARSAW              21
344       VINCENNES              20
146          HOBART              17
222   MICHIGAN CITY              16
144        HIGHLAND              16
230       MISHAWAKA              16
44       CHESTERTON              15
162     INDIANPOLIS              15
352       WALKERTON              15
275      PLAINFIELD              15

In [20]:
# Calculate additional metric to filter for strange anamolies in data 
city_donantion_amounts = indiana_donations.groupby('CITY')['TRANSACTION_AMT'].sum().reset_index(name='DONATION_AMT')

In [21]:
#------one of the strange things about the top 41 donating cities in indiana(other than the significant outlier)

# Filter for cities with "lafayette" in the name (case-insensitive)
# The na=False parameter prevents errors with NaN values
lafayette_cities = city_donantion_amounts[city_donantion_amounts['CITY'].str.contains('lafayette', case=False, na=False)]
print("\nCities containing 'lafayette' (any capitalization):")
print(lafayette_cities)

# Count donations for lafayette cities (safely handling NaN values)
lafayette_donation_counts = indiana_donations[
    indiana_donations['CITY'].str.contains('lafayette', case=False, na=False)
].groupby('CITY').size().reset_index(name='DONATION_COUNT')
print("\nDonation counts for Lafayette cities:")
print(lafayette_donation_counts)

Cities containing 'lafayette' (any capitalization):
               CITY  DONATION_AMT
188       LAFAYETTE         49851
347     W LAFAYETTE         10350
358  WEST LAFAYETTE         12840

Donation counts for Lafayette cities:
             CITY  DONATION_COUNT
0       LAFAYETTE              85
1     W LAFAYETTE              22
2  WEST LAFAYETTE              24

In [22]:
def longesttest (mydata: pd.Series) -> str:
    """
    The longesttest function takes a Pandas Series as input,
    containing strings, and returns the longest string.

    Args:
    mydata (pd.Series): This is any type of Series that contains strings which we want to study,

    Returns:
    mylongeststring (str): This is the longest of the strings in the Pandas Series
    """
    mylongeststring = max(mydata, key=len)
    return mylongeststring

In [23]:
# Display resutls after running user defined function "longesttest" on 'NAME' column from the dataframe

In [24]:
longesttest(myElection_Donations['NAME'].astype(str))

'REPUBLICAN NATIONAL COMMITTEE - CONTRIBUTIONS (AKA REPUBLICAN NATIONAL FINANCE COMMITTEE'